### ISSUE TITLE
command 'codemetrics.toggleCodeMetricsDisplayed' not found

### ISSUE THREAD

**Issue by yuanoook** [kisstkondoros/codemetrics#51] opened 2018-02-22 03:12 UTC
I get this when I try `> toggle code metrics`
```
command 'codemetrics.toggleCodeMetricsDisplayed' not found
```

**Comment by kisstkondoros** [comment] 2018-02-22 20:59
Could you please elaborate on this?
extension version
vscode version (please also include whether is it an insider version)
do you have an active file editor open?
is it an issue in every file type?
...

**Comment by kisstkondoros** [comment] 2018-02-25 12:14
I suspect that some activation event was not fired so the command contributions were not resolved, but I couldn't reproduce the issue locally.

I'm closing this now, but please file another ticket (with the requested information) if the problem still occurs.

**Closed by kisstkondoros** 2018-02-25 12:14 UTC
