### ISSUE TITLE
Extensions spawns extra electron server

### ISSUE THREAD

**Issue by bm-stschneider** [kisstkondoros/codemetrics#59] opened 2018-09-18 14:17 UTC
in 
https://github.com/Microsoft/vscode/issues/58166#issuecomment-422407857
the problem came up, after investigating on which extension leads to the issue it seems to be code metrics.
After uninstalling the extension the problem was gone.

**Comment by kisstkondoros** [comment] 2018-09-22 12:59
Hi,

Yes the extension starts a server in order to keep the editor responsive. The heavy lifting is done in that process, that is the recommended way to do it.

As I've saw in the linked issue the problem is not that the process is spawned, but that it consumes too much CPU.

Now that is something I could potentially help with, but the details are far from enough to reproduce it. 

Could you perhaps provide a repo where the problem occurs?

**Comment by bm-stschneider** [comment] 2018-09-24 06:03
I'm afraid I can not because it is a private repo. Also this happened when I rebuild some of the files, maybe the process is too greedy in watching files?

**Comment by kisstkondoros** [comment] 2018-09-24 10:08
Based on my tests the extension does what it should in the least greedy way:
There is no filesystem watcher configured.
Text documents are only synced when they get opened and the synchronization is stopped if they are closed - for this I use the API provided by the language server.
etc.

As far as I'm concerned this problem should not be caused by this extension.

I'm closing this for now, but if you could provide a "Minimal Complete Verifiable Example" I'm happy to reopen this.

**Closed by kisstkondoros** 2018-09-24 10:08 UTC
