### ISSUE TITLE
Nothing happen with vscode 1.10.2 on osx

### ISSUE THREAD

**Issue by lucap86** [kisstkondoros/codemetrics#17] opened 2017-03-25 10:39 UTC
Hi all,
I cannot see metrics info, 
toggle code metrics doesn't produce any info.

osx 10.11.6
vscode 1.10.2
extension version 1.2.2

**Comment by kisstkondoros** [comment] 2017-03-26 06:05
Thanks for the issue report!
Unfortunately I can't reproduce it (I don't own a macOS).
I've tried however with vscode 1.10.2 and extension version 1.2.2.

Toggle code metrics is intended to hide the metrics information, so it should be visible after a fresh start of vscode. So there is no need to run any command to see the complexity metrics.

It might also be that the typescript compiler can not parse the file for some reason.

To be able to solve the issue I would need the following information:
- Typescript / JavaScript version in use
- Are there any special characters on the path?
- Anything special with the project / files? (Is it on a network drive? etc.)
- What other extensions are installed?
- Do you encounter this problem on another code base as well? (e.g. when opening the source of this extension)
- Worked for You before version 1.2.2?
- Can you attach the workspace and user settings of vscode?

Thanks in advance!

**Comment by kisstkondoros** [comment] 2017-03-31 17:30
I'll close it because of absence of information (I guess the toggle command was executed rendering code metrics non-visible)
If this is not the case please open a new issue with more details.

Thank you!

**Closed by kisstkondoros** 2017-03-31 17:30 UTC
